
spring: 
  main: 
    web-environment: false
  redis: 
    #host: 192.168.0.209
    host: wulinThinkPad
    port: 6379
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-active: 600
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: -1
      # 连接池中的最大空闲连接 默认 8
      max-idle: 600
      # 连接池中的最小空闲连接 默认 0
      min-idle: 100
        
