/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_wulin_brace_jni_HelloJni */

#ifndef _Included_cn_wulin_brace_jni_HelloJni
#define _Included_cn_wulin_brace_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_wulin_brace_jni_HelloJni
 * Method:    say
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_wulin_brace_jni_HelloJni_say
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
